
datos.entreno.alg<-dplyr::select(datos.entreno,
                                 S_weekday                              ,
                                 # S_sleeponset_ts                        ,
                                 # S_wakeup_ts                            ,
                                 # S_L5TIME                               ,
                                 # D_caffeine                             ,
                                 # D_sleep_time                           ,
                                 # D_slowness_fill_form                   ,
                                 # D_sleep_duration                       ,
                                 # D_sleep_zenith                         ,
                                 # D_observation_string_length            ,
                                 # D_time_start_form                      ,
                                 # D_slowness_fill_form_no_outliers       ,
                                 # D_slowness_fill_form_no_outliers_scales,
                                 # S_window_number                        ,
                                 # S_sleeponset                           ,
                                 # S_wakeup                               ,
                                 # S_night_number                         ,
                                 # S_nonwear_perc_spt                     ,
                                 # S_nonwear_perc_day_spt                 ,
                                 # S_dur_spt_sleep_min                    ,
                                 # S_dur_spt_wake_IN_min                  ,
                                 # S_dur_spt_wake_LIG_min                 ,
                                 # S_dur_spt_wake_MOD_min                 ,
                                 # S_dur_day_LIG_unbt_min                 ,
                                 # S_dur_day_MOD_unbt_min                 ,
                                 # S_dur_day_MVPA_bts_1_min               ,
                                 # S_dur_day_IN_bts_30_min                ,
                                 # S_dur_day_IN_bts_10_30_min             ,
                                 # S_dur_day_IN_bts_1_10_min              ,
                                 # S_dur_day_LIG_bts_10_min               ,
                                 # S_dur_day_LIG_bts_1_10_min             ,
                                 # S_dur_day_total_IN_min                 ,
                                 # S_dur_day_total_LIG_min                ,
                                 # S_dur_day_total_MOD_min                ,
                                 # S_dur_day_min                          ,
                                 # S_dur_spt_min                          ,
                                 # S_dur_day_spt_min                      ,
                                 # S_sleep_efficiency                     ,
                                 # S_ACC_spt_sleep_mg                     ,
                                 # S_ACC_spt_wake_IN_mg                   ,
                                 # S_ACC_spt_wake_LIG_mg                  ,
                                 # S_ACC_spt_wake_MOD_mg                  ,
                                 # S_ACC_day_IN_unbt_mg                   ,
                                 # S_ACC_day_LIG_unbt_mg                  ,
                                 # S_ACC_day_MOD_unbt_mg                  ,
                                 # S_ACC_day_VIG_unbt_mg                  ,
                                 # S_ACC_day_MVPA_bts_1_mg                ,
                                 # S_ACC_day_IN_bts_30_mg                 ,
                                 # S_ACC_day_IN_bts_10_30_mg              ,
                                 # S_ACC_day_IN_bts_1_10_mg               ,
                                 # S_ACC_day_LIG_bts_10_mg                ,
                                 # S_ACC_day_LIG_bts_1_10_mg              ,
                                 # S_ACC_day_total_IN_mg                  ,
                                 # S_ACC_day_total_LIG_mg                 ,
                                 # S_ACC_day_total_MOD_mg                 ,
                                 # S_ACC_day_total_VIG_mg                 ,
                                 # S_ACC_day_mg                           ,
                                 # S_ACC_spt_mg                           ,
                                 # S_ACC_day_spt_mg                       ,
                                 # S_quantile_mostactive60min_mg          ,
                                 # S_quantile_mostactive30min_mg          ,
                                 # S_L5VALUE                              ,
                                 # S_M5VALUE                              ,
                                 # S_L5TIME_num                           ,
                                 # S_M5TIME_num                           ,
                                 # S_L10VALUE                             ,
                                 # S_M10VALUE                             ,
                                 # S_L10TIME_num                          ,
                                 # S_M10TIME_num                          ,
                                 # S_Nbouts_day_IN_bts_30                 ,
                                 # S_Nbouts_day_IN_bts_1_10               ,
                                 # S_Nbouts_day_LIG_bts_10                ,
                                 # S_Nbouts_day_LIG_bts_1_10              ,
                                 # S_Nblocks_spt_sleep                    ,
                                 # S_Nblocks_spt_wake_IN                  ,
                                 # S_Nblocks_spt_wake_LIG                 ,
                                 # S_Nblocks_spt_wake_MOD                 ,
                                 # S_Nblocks_day_LIG_unbt                 ,
                                 # S_Nblocks_day_MOD_unbt                 ,
                                 # S_Nblocks_day_IN_bts_30                ,
                                 # S_Nblocks_day_IN_bts_1_10              ,
                                 # S_Nblocks_day_LIG_bts_1_10             ,
                                 # S_Nblocks_day_total_IN                 ,
                                 # S_Nblocks_day_total_LIG                ,
                                  S_Nblocks_day_total_MOD,
                                 E_diagnosis)

datos.entreno.alg.ld<-datos.entreno.alg[ , -which(names(datos.entreno.alg) %in% var_diagnosis)]
datos.entreno.alg.ld<-as.matrix(datos.entreno.alg.ld)
targ<-datos.entreno.alg[[var_diagnosis]]



modelo_ld<-cv.glmnet(datos.entreno.alg.ld,targ,family='multinomial', type.measure='class', nfolds=148)